version: "3.8"

services:
    postgres:
        image: postgres:17-alpine
        container_name: postgres-laravel
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: belajar_laravel
            TZ: Asia/Jakarta
        ports:
            - "5435:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - laravel-network

volumes:
    postgres_data:
        driver: local

networks:
    laravel-network:
        driver: bridge
